### ISSUE TITLE
on functions not working

### ISSUE THREAD

**Issue by MrWeit** [razorRun/react-native-vlc-media-player#1]
Hi,
when i try to use the on functions like the onPlaying function it doesn't work, im streming a rtsp video.
Thanks

**Comment by sayem314** [comment]
Yes exactly. None of these actually work.

```js
           onProgress={this.onProgress.bind(this)}
           onEnd={this.onEnded.bind(this)}
           onBuffering={this.onBuffering.bind(this)}
           onError={this._onError}
           onStopped={this.onStopped.bind(this)}
           onPlaying={this.onPlaying.bind(this)}
           onPaused={this.onPaused.bind(this)}
```

**Comment by razorRun** [comment]
Hey Guys
I am bit packed these days, Can anyone update the android vlc kit ?

**Comment by ammarahm-ed** [comment]
@razorRun I will update vlc version and send a pull request.

**Comment by ammarahm-ed** [comment]
Also the implementation for events on android is different than that on `ios` which should be corrected. Events are called but all events come through a single event `onVideoStateChange` which is absurd because the JS side does not implement it.

**Comment by razorRun** [comment]
@ammarahm-ed  thanks mate.  Note that I already have updated IOS side (use 3.3.10). Also no need to to do the react link as done the pod spec.

**Comment by ammarahm-ed** [comment]
@razorRun  yes that is better.

**Comment by razorRun** [comment]
@ammarahm-ed  invited you as a contributor. 
❤️👏 for your PR

BTW on the PR, does it build without an issue? I am having a bit of trouble on that on [this](https://github.com/razorRun/react-native-vlc-media-player-test) source(RN 61.0.5). could you test when you get a second? Our idea was to keep the repo so simple, people can use it with RN newer versions without any additional config.

**Comment by ammarahm-ed** [comment]
Yes it builds normally. I have tested it in your example app before sending the pull-request. @razorRun

**Comment by sayem314** [comment]
I have hard forked the original yz-vlc-player and added some stuff from this one. My fork uses VLC 3.2.6 and all of this work as well:

```
onProgress
onSeek
onError
onStopped
.seek()
```

Btw the reason I have forked is to be able to use it on Lunarr app with `react-native-video` like props.

**Comment by razorRun** [comment]
💪 Do you mind merging it ?

**Comment by sayem314** [comment]
>  Do you mind merging it ?

Well, it can't be merged directly, there are huge differences between this and lunarr-vlc-player. And you will lose the player view as well. The best option would be to merge manually those files one by one here.

**Comment by ammarahm-ed** [comment]
@razorRun I will fix the event system on android in a couple of days and send a pull request. 

@sayem314 is AspectRatio working? something like resizeMode in react-native-video?

**Comment by razorRun** [comment]
@ammarahm-ed Thanks, Mate. Feel free to merge it as well. You should have access rights

**Comment by sayem314** [comment]
> @sayem314 is AspectRatio working? something like resizeMode in react-native-video?

Yes, changing aspect ratio should work. Make sure you are dividing it by colon (:) and it's a string. 

Example:
```js
videoRef.current.changeVideoAspectRatio('1:1')
```

And resizeMode is not available.

**Comment by ammarahm-ed** [comment]
@sayem314  I think that the aspectRatio prop is absurd and should not exist. The aspectRatio of the video should be calculated automatically and should be correct always. Also there should be something like resizeMode as it is in react-native-video instead which will be very useful. I have implemented it in my react-native-ijkvideo component on android. I think its not that difficult to do.

**Comment by sayem314** [comment]
> @sayem314 I think that the aspectRatio prop is absurd and should not exist. The aspectRatio of the video should be calculated automatically and should be correct always. Also there should be something like resizeMode as it is in react-native-video instead which will be very useful. I have implemented it in my react-native-ijkvideo component on android. I think its not that difficult to do.

Yes, you are right about that but I kept as it was on the `yz-vlc` and it was just a hard fork. I didn't care to remove it since I don't even use it but yes will remove it in future version and will try to add `resizeMode` props. BTW aspect ratio is currently calculated automatically.

**Comment by ammarahm-ed** [comment]
lets see if we can implement resizeMode here.

**Comment by MrWeit** [comment]
Well i think the problem is fixed thx guys
