### ISSUE TITLE
Can I commit some changes?

### ISSUE THREAD

**Issue by yuebaiqinghui** [razorRun/react-native-vlc-media-player#100]
I have changed some codes in VLCPlayerView.js SizeController.js and index.js
these changes work for adding 'onError' function in <VLCPlayerView> and fix the bug (when video playing on the Full screen mobile phone in Landscape mode,there are some blanks at the top of phone

**Comment by razorRun** [comment]
Sure mate. Just fork it and send PR through. 💪💪
