### ISSUE TITLE
incompatible with Gradle 8.0

### ISSUE THREAD

**Issue by raajjemv** [razorRun/react-native-vlc-media-player#101]
<img width="1311" alt="Screen Shot 2022-02-16 at 11 13 16 PM" src="https://user-images.githubusercontent.com/36122879/154329230-fef0ac94-b195-456e-a726-b553b220abc6.png">

react-native: 0.67.2

it works perfectly with ios.

**Comment by youcci** [comment]
Any Updates on that?
My App works on iOS but Android is not working at all

**Comment by longphung** [comment]
@raajjemv Hi if this is still a problem for you then the author has posted the fix. As the error stated, `libc++_shared.so` was found on 2 files.  

This snippet was included in the README to remove one of the duplicate `libc++_shared.so`, on `jetified-react-native` file.
```groovy
tasks.whenTaskAdded((tas -> {
    // when task is 'mergeLocalDebugNativeLibs' or 'mergeLocalReleaseNativeLibs'
    if (tas.name.contains("merge") && tas.name.contains("NativeLibs")) {
        tasks.named(tas.name) {it
            doFirst {
                java.nio.file.Path notNeededDirectory = it.externalLibNativeLibs
                        .getFiles()
                        .stream()
                        .filter(file -> file.toString().contains("jetified-react-native"))
                        .findAny()
                        .orElse(null)
                        .toPath();
                Files.walk(notNeededDirectory).forEach(file -> {
                    if (file.toString().contains("libc++_shared.so")) {
                        Files.delete(file);
                    }
                });
            }
        }
    }
}))
```
Be mindful though as on the latest `react-native` version the file is not named `jetified-react-native` anymore if you enabled `hermes`. It is `jetified-react-android` instead.

**Comment by racedaemon** [comment]
I get the following error when adding this block of code to android/app/build.gradle:
```
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not get unknown property 'Files' for task ':app:mergeDebugNativeLibs' of type com.android.build.gradle.internal.tasks.MergeNativeLibsTask.
``` 

Tried to figure it out by myself but my Java and Groovy skills are lacking.

Using react-native 0.70.6

Any ideas?

i also get a syntax error in the editor but i'm not sure it is linked:
![image](https://user-images.githubusercontent.com/8333497/227177556-bfdaf3d4-e4d2-42e2-bfdd-01fe1094c9a0.png)

**Comment by longphung** [comment]
You need to import Files. Add this line to the top of your `build.gradle`:
```java
import java.nio.file.Files
```
