### ISSUE TITLE
App keeps crashing on IOS simulator

### ISSUE THREAD

**Issue by aircliff01** [razorRun/react-native-vlc-media-player#102]
Hi I tried using the player and my app keeps on crashing everytime I try to re-render the player view. Any ideas what could be happening?

**Comment by Krunal-K-SimformSolutions** [comment]
Any update?, because I have the same issue.

**Comment by razorRun** [comment]
Have you tried the sample app? We use this on a app and doesn’t crash.

**Comment by Krunal-K-SimformSolutions** [comment]
@razorRun: Yes, it works, also try with a fresh project, and working fine but I don't know why when I am implementing my project the app crashes.

**Comment by razorRun** [comment]
Are you passing the params for android and ios separately as in the sample?
what about bit encoding on ios? Try on a real device ?

**Comment by kelvinaliyanto** [comment]
I am using ios simulator on ios 17.4, and it also crashes with Thread 35: EXC_BAD_ACCESS (code=2, address=0x11ee5c000). Anyone facing the same issue? It works fine in real device.

**Comment by zbarbuto** [comment]
FTR solution for me was to use an iOS 18+ simulator. See [here](https://code.videolan.org/videolan/VLCKit/-/issues/724#note_443338).

Have created #252 to add this to the docs.
