### ISSUE TITLE
How to snapshot both android and ios using  react-native-vlc-media-player?

### ISSUE THREAD

**Issue by vinhnq90** [razorRun/react-native-vlc-media-player#104]

**Comment by vinhnq90** [comment]
Hi everyone, I want to take screenshot videoview when play camera. In source code, I see script below in "ReactVlcPlayerView.java" but there are no body. Who can help me please?
    public void doSnapshot(String path) {
        return;
    }

**Comment by razorRun** [comment]
Hey

That player view have bit of issues that need to be fixed. And I won’t be
able to get to this for next couple of months. Maybe log a bug bounty have
a look at it your self? I will merge any pr as soon as they are available
and happy to help out anyone trying to fix things
