### ISSUE TITLE
IOS Buffering data issue

### ISSUE THREAD

**Issue by pandiarajanvp** [razorRun/react-native-vlc-media-player#105]
On IOS onBuffering data its return only {"target": 13099} ,How to get buffer is completed or not

**Comment by ZhminkoRoman** [comment]
The same =(

**Comment by roshansinghg** [comment]
> On IOS onBuffering data its return only {"target": 13099} ,How to get buffer is completed or not

hi @pandiarajanvp , have you found the solution for this ?

**Comment by PervezBellary** [comment]
> On IOS onBuffering data its return only {"target": 13099} ,How to get buffer is completed or not

HI @pandiarajanvp  any solution for this...?
