### ISSUE TITLE
Apple store team rejected app due to Deprecated UIWebView API usage

### ISSUE THREAD

**Issue by priyankagupta23pg** [razorRun/react-native-vlc-media-player#107]
On publishing the application on app store using this library, App store team rejected app with below message. Please suggest someone---

**ITMS-90809: Deprecated API usage** 
New apps that use UIWebview are no longer accepted. Instead, use WKWebView for improved security & reliability

I am using the latest version- 
 "react-native-vlc-media-player": "^1.0.40",

**Comment by danielakarwowska** [comment]
Hi, The same problem but with eas update command. Did you find any solution?
