### ISSUE TITLE
Build fails on android

### ISSUE THREAD

**Issue by endrits079** [razorRun/react-native-vlc-media-player#110]
When running npm run android the build fails with the message:

A problem occurred evaluating project ':react-native-vlc-media-player'.
> Could not find method provided() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler

* Where:
Build file 'path-to-project/node_modules/react-native-vlc-media-player/android/build.gradle' line: 32.

versions:
react native: 0.66.4
react-native-vlc-media-player: ^1.0.40

**Comment by endrits079** [comment]
The problem was gradle version was using 7.0.1 changed to 4.2.2

**Comment by viaDPBell** [comment]
I also faced the same problem.
did you solve this problem?

**Comment by endrits079** [comment]
> I also faced the same problem. did you solve this problem?

yes, by downgrading gradle version to 4.2.2 (because I was on version 7) and then open project with android studio, and do gradle sync after clean the project and it should be working
