### ISSUE TITLE
Cannot make video fill the whole screen?

### ISSUE THREAD

**Issue by endrits079** [razorRun/react-native-vlc-media-player#111]
There is black space left on top and bottom of the screen, I want to make the video fill the entire screen this is the styles that I applied
{
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: deviceWidth,
    height: deviceHeight,
    zIndex: -1,
  }
  
  and  tried all the options for resizeMode but none worked

**Comment by slodhi786** [comment]
same issue here. using react-native-vlc-media-player@1.0.57

**Comment by igorbacz** [comment]
The same issue. Any possibility to turn on full screen view ?
