### ISSUE TITLE
A problem occurred evaluating project ':react-native-vlc-media-player'.

### ISSUE THREAD

**Issue by Hull95** [razorRun/react-native-vlc-media-player#112]
A problem occurred evaluating project ':react-native-vlc-media-player'.
> Could not find method provided() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

react-native version is 0.68.1

**Comment by IndrakumarR** [comment]
> A problem occurred evaluating project ':react-native-vlc-media-player'.
> 
> > Could not find method provided() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> react-native version is 0.68.1

Same issue for me also

**Comment by CrhistianDLM** [comment]
Me too
