### ISSUE TITLE
Cannot read properties of undefined (reading 'VlCPlayerView')

### ISSUE THREAD

**Issue by nguyenhuynhdeveloper** [razorRun/react-native-vlc-media-player#118]
Cannot read properties of undefined (reading 'VlCPlayerView')

i  have issue, can help me

**Comment by JYFlows** [comment]
me too 
did you solve it ？

**Comment by Bilal12C** [comment]
me too
did you solve it ？

**Comment by dongchuanlei** [comment]
me too
did you solve it ？
