### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.Image.propTypes.source')

### ISSUE THREAD

**Issue by mousumi88** [razorRun/react-native-vlc-media-player#132]
Hi I am facing the following error after installing react-native-vlc-media-player. My react native version is "react-native": "0.69.2".
App has not been started due to this error. The complete error message is :

`ERROR  TypeError: undefined is not an object (evaluating '_reactNative.Image.propTypes.source')`
 `ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.`

This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

If I remove the following line then issue solved:
import { VLCPlayer } from 'react-native-vlc-media-player;

But I have to import VLCPlayer for playing .webm video in ios. I am working in IOS platform. Please help me to solve the issue.

**Comment by Yami01** [comment]
I'm facing the same issue :(

**Comment by mdilshan** [comment]
What version of `react-native-vlc-media-player` do you use ?
