### ISSUE TITLE
Any idea whats going on? I can't build the app at all

### ISSUE THREAD

**Issue by aitoncumbi** [razorRun/react-native-vlc-media-player#134]
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - C:\Users\aiton\.gradle\caches\transforms-3\0b825f9a3cd84cf1738e48fbfed11fea\transformed\jetified-react-native-0.70.6-debug\jni\arm64-v8a\libc++_shared.so
      - C:\Users\aiton\.gradle\caches\transforms-3\db8b0603db3af202dc8212f24571f0ff\transformed\jetified-libvlc-all-3.1.12\jni\arm64-v8a\libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

    at makeError (C:\Users\aiton\Projects\GitHub\cfm_iguard_mobile\node_modules\execa\index.js:174:9)
    at C:\Users\aiton\Projects\GitHub\cfm_iguard_mobile\node_modules\execa\index.js:278:16
    at async runOnAllDevices (C:\Users\aiton\Projects\GitHub\cfm_iguard_mobile\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\aiton\Projects\GitHub\cfm_iguard_mobile\node_modules\@react-native-community\cli\build\index.js:142:9)

**Comment by razorRun** [comment]
Arm issue on M1 chipset? Try pulling the test repo see what happens?
