### ISSUE TITLE
How can I select the audio tracks and subtitles?

### ISSUE THREAD

**Issue by Arekjaar4** [razorRun/react-native-vlc-media-player#137]
How can I select the audio tracks and subtitles?
The documentation indicates that it is supported but does not indicate how to obtain or select them

Supported formats
Support for network streams, RTSP, RTP, RTMP, HLS, MMS. Play all files, in all formats, including exotic ones, like the classic VLC media player. **Play MKV, multiple audio tracks (including 5.1), and subtitles tracks (including SSA!)**

**Comment by Arnoldnuo** [comment]
You can use my pr to support subtitles: https://github.com/razorRun/react-native-vlc-media-player/pull/143

**Comment by razorRun** [comment]
This PR Is merged now. Please test and let us know

Cheers

**Comment by Arekjaar4** [comment]
Are you referring to the "subtitleUri" property?
I do not need this. What I need is to be able to select the audio, video and subtitle tracks just like the react-native-video library does with the properties, selectedAudioTrack,
selectedTextTrack
and
selectedVideoTrack
[https://github.com/react-native-video/react-native-video/blob/master/API.md#selectedaudiotrack](url)

**Comment by GZLiew** [comment]
@Arnoldnuo https://github.com/razorRun/react-native-vlc-media-player/pull/143 crashed my app what changed?

**Comment by YadongChen** [comment]
Sorry for opening again and leaving a message after a long time in the past

After I used the PR related to this Issue, the project reported an error
https://github.com/razorRun/react-native-vlc-media-player/pull/144 

project environment：XCode 14.x & react-native 0.68.x & Android Gradle 7.x

Error details：

Bugs are reported in the newly added code section in：mediaPlayerTimeChanged - case VLCMediaPlayerStateBuffering 
![react-native-vlc-media-player-issue-02](https://github.com/razorRun/react-native-vlc-media-player/assets/49865419/e7ab9148-ac5e-466e-9e93-e35fb7576d26)

It seems that in some cases the self.onVideoLoad method itself does not exist when VLCMediaPlayerStateBuffering is triggered
(The reason has not been investigated yet)

For reference, my current solution is:

(1) Roll back the version to before this PR: for example 1.0.49

(2) Patch this package, and add fault-tolerant judgment null value processing at the above-mentioned self.onVideoLoad call

-------------------------------------

很抱歉过去很久再次打开并留言

我在使用到此Issue相关的PR: https://github.com/razorRun/react-native-vlc-media-player/pull/144 后，项目出现了报错

项目环境：XCode 14.2+ & react-native 0.68.x & Android Gradle 7.x

错误详细：

错误被报告在：mediaPlayerTimeChanged - case VLCMediaPlayerStateBuffering 中新增的代码部分

似乎在某些情况下，触发VLCMediaPlayerStateBuffering时，self.onVideoLoad方法本身并不存在
（还未真正的调查到原因）

以供参考，我目前的解决方案是：

（1）回退版本至本次PR前：例如 1.0.49

（2）patch此package，在上述的self.onVideoLoad调用处增加容错判断空值处理
