### ISSUE TITLE
How can I control subtitle.

### ISSUE THREAD

**Issue by amerllica** [razorRun/react-native-vlc-media-player#15]
I'm worried about the subtitle, both soft-sub or link-sub. How I can deal with them on this package?

**Comment by Shashank2406** [comment]
> I'm worried about the subtitle, both soft-sub or link-sub. How I can deal with them on this package?

+1

**Comment by amerllica** [comment]
Dear @Shashank2406, please do not worry, I'm writing a new player based on VLC docs for both `iOS` and `Android` operating systems. this will be based on new technologies. just wait a while.

**Comment by Zenyker** [comment]
@amerllica didi you finish the player, I don't know how to get the list of audio and subtitles from a mkv file.

**Comment by amerllica** [comment]
@Zenyker, Hi not yet, actually, I'm working on a big scale project, and the flow of writing a new player is stopped right now, the issue comes from time, If I work on it for two weeks full-time I can finish it for both iOS and Android side, but now just iOS is ready and also we didn't publish it.

[Current iOS](https://github.com/iran-react-community/react-native-ir-player/tree/init-vlckit-ios-swift): you can check it now.

**Comment by DevineDecrypter** [comment]
@amerllica im checking ur profile every day hoping for the player to be finished

**Comment by amerllica** [comment]
@DevineDecrypter, I'm very busy with a large-scale project and for now, I cannot put time for it, but I will in three or four months later, do not check my profile, check [here](https://github.com/iran-react-community/react-native-ir-player/tree/init-vlckit-ios-swift). The iOS side is mostly finished, but about the Android side, we didn't even start it.

**Comment by DevineDecrypter** [comment]
@amerllica ok , good luck on your project . Mamnoon :)
