### ISSUE TITLE
'TVVLCKit/TVVLCKit.h' file not found

### ISSUE THREAD

**Issue by superyzr** [razorRun/react-native-vlc-media-player#152]
when i use [react-native-vlc-media-player@1.0.52] and the project error reporting (in target 'react-native-vlc-media-player' from project 'Pods') 
and Xcode reporting 'TVVLCKit/TVVLCKit.h' file not found

System environment：
macOS  13.2.1
Node.js v19.9.0
react-native 0.71.7
iPhone 14 Pro Max  iOS 16.4

**Comment by Duell10111** [comment]
Should be fixed with https://github.com/razorRun/react-native-vlc-media-player/pull/154

**Comment by superyzr** [comment]
thanks for you job
