### ISSUE TITLE
iOS: App crashes after last update

### ISSUE THREAD

**Issue by AlejandroAguilar99** [razorRun/react-native-vlc-media-player#153]
Hi! We updated this package to its last version bc it crashed on Android 12 & 13 and that problem got solved, but that caused that the app crashes whenever we open a screen that contains this component on ios, why would that be happening? is there any configuration or code block that we should add just like android required?

**Comment by Duell10111** [comment]
Could be fixed with https://github.com/razorRun/react-native-vlc-media-player/pull/154
