### ISSUE TITLE
Crash on android: can't load vlcjni library

### ISSUE THREAD

**Issue by yenpn** [razorRun/react-native-vlc-media-player#158]
`Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__sfp_handle_exceptions" referenced by "/data/app/~~1bfBT3SfYyfXSkyMkDorcQ==/com.ppface-JFrgxUkS2PEi9O55p5BT9g==/lib/arm64/libvlc.so"...`

Please help me resolve above error on android, work fine on IOS:
I'm using:
- "react-native": "^0.71.7"
- "react-native-vlc-media-player": "1.0.53"

**Comment by yenpn** [comment]
I'm resolved after change jetified-react-native to jetified-react-android in tasks.whenTaskAdded

**Comment by hoangnv170752** [comment]
I still got this problems on android 13 @yenpn
