### ISSUE TITLE
The onProgress callback on Android

### ISSUE THREAD

**Issue by amerllica** [razorRun/react-native-vlc-media-player#16]
The `onProgress` callback doesn't work on Android.

**Comment by amerllica** [comment]
By reading [this file](https://github.com/razorRun/react-native-vlc-media-player/blob/master/android/src/main/java/com/yuanzhou/vlc/vlcplayer/ReactVlcPlayerView.java) I realized that the `mProgressUpdateRunnable` doesn't work, or maybe is not used anywhere and because of this, the `onProgress` doesn't work on the **Android** side.

**Comment by razorRun** [comment]
this issue should be fixed thanks to [vokhuyetOz ](https://github.com/razorRun/react-native-vlc-media-player/pull/21)

**Comment by vokhuyetOz** [comment]
@amerllica if you still face this issue, feel free to give your feedback.
