### ISSUE TITLE
index.d.ts type definition file needed

### ISSUE THREAD

**Issue by Disfractal** [razorRun/react-native-vlc-media-player#161]
Tried using this with a Typescript based project and it didn't work. I tried creating a typescript file but the player crashes the app with no error thrown on start.

**Comment by usmanmalik333** [comment]
I'm also facing this same issue 
got this error on the import statement :
Could not find a declaration file for module 'react-native-vlc-media-player'. 'd:/IdeoProjects/V3 RNS/new project/rns_v3/node_modules/react-native-vlc-media-player/index.js' implicitly has an 'any' type.
@Disfractal @vgaicuks @Duell10111 @whck6 @alexfrompiter

**Comment by adok0001** [comment]
Got this same issue. It's imperative for a ts app. @Disfractal @usmanmalik333 did anyone get any work done on it? I'm down to contribute

**Comment by Disfractal** [comment]
@adok0001 Sorry for the late response I forgot your message. So this was a huge issue and undertaking to figure it out. After a month or so of research it became apparent that this library is outdated and it needed to be rebuilt using the latest react-native frameworks. I started work on rebuilding it but the contract it was for was cancelled and I stopped work.
