### ISSUE TITLE
Crash when production apk/aab

### ISSUE THREAD

**Issue by abdoerrahiem** [razorRun/react-native-vlc-media-player#162]
Working fine on development, but on production app crash when show video.
I use react native 0.70.6.
Any idea?

**Comment by notjulian** [comment]
me too

but with 1.0.48 it works

**Comment by QuangNguyen240498** [comment]
is this fix yet everyone ?

**Comment by tunm1228** [comment]
You can update to file **build.gradle** implementation 'org.videolan.android:libvlc-all:3.6.0-eap9'

**Comment by QuangNguyen240498** [comment]
> You can update to file **build.gradle** implementation 'org.videolan.android:libvlc-all:3.6.0-eap9'

Thks, it works for me
