### ISSUE TITLE
VLC-Media-Player not founded and doesn't work for RTSP in RN APP

### ISSUE THREAD

**Issue by gabrielzopz** [razorRun/react-native-vlc-media-player#170]
I'm trying to stream a RTSP IP Camera but the Lib is not compatible with RN 70+ and i can't even render a component via Expo Go.
It appears the issue: "RCTVLCPlayer" was no found in the UIManager.

**Comment by gstcarv** [comment]
This library can't be used in a Expo GO based application because it requires native code to work. But if you really want, you can try development build as described [here](https://github.com/razorRun/react-native-vlc-media-player#expo).

in app.json:

```json
{
    "plugins": [
         "react-native-vlc-media-player"
    ]
}
````

**Comment by gabrielzopz** [comment]
Boa tarde amigo.

Pelo nome acredito que seja brasileiro então falar português é mais fácil.

Eu to tentando fazer como sugerido mas não to conseguindo, poderia entrar
em contato pelo whatspp pra gente poder conversar melhor?

Obrigado!

(24)9 8122-7084

Em qua., 23 de ago. de 2023 às 21:54, Gustavo Carvalho <
***@***.***> escreveu:
