### ISSUE TITLE
Expo-generated apk gets heavy with this library

### ISSUE THREAD

**Issue by MatteoBuffo** [razorRun/react-native-vlc-media-player#171]
Hello. I'm currently working on an Expo app (bare workflow) and whenever I generate a development build (development profile) the resulting apk size is around 75 MB (that's ok).

After the installation of react-native-vlc-media-player, the apk size is over 160 MB.

Is there a way to prevent this? Thanks in advance.

**Comment by MatteoBuffo** [comment]
Solved by following [this](https://github.com/razorRun/react-native-vlc-media-player/issues/48#issuecomment-1005522002).

**Comment by ReeceKenney** [comment]
Do you know if this can be achieved using an expo managed workflow?

**Comment by buildnewapp** [comment]
add build config 
android/app/build.gradle



    defaultConfig {
        applicationId 'com.xxx.app'
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0"

        buildConfigField("boolean", "REACT_NATIVE_UNSTABLE_USE_RUNTIME_SCHEDULER_ALWAYS", (findProperty("reactNative.unstable_useRuntimeSchedulerAlways") ?: true).toString())

        ndk {
            abiFilters 'armeabi-v7a'
        }
    }
