### ISSUE TITLE
How to display the slider in the VlCPlayerView?

### ISSUE THREAD

**Issue by mvortizr** [razorRun/react-native-vlc-media-player#173]
Hi, I am using the library and I can't figure out how to add the slider on the VLCPlayerView... 

This is my code
```javascript
       <VlCPlayerView
                    url={props.videoUri}
                    autoplay={true}
                    isGG={false}
                    showGG={false}
                    Orientation={Orientation}
                    autoAspectRatio={true}
                    resizeMode="cover" 
                    repeat={true}
                    isFull={true}
                    seek={0}
                    realShowLoding={true}
                    showControls ={true}
                    showRightButton={false}
             />
    );
``` 

This is how it shows
![image](https://github.com/razorRun/react-native-vlc-media-player/assets/25888607/c3ff63e3-96ce-45e7-8daf-928735529fc8)

I want something to tell how much of that video I've seen but I can't figure out how to make the slider show. I see in the library code something with GG and I have no idea what it means. I am trying using isGG set to false but it isn't working
![image](https://github.com/razorRun/react-native-vlc-media-player/assets/25888607/3850e689-13f4-4387-bf67-710451fb0d23)

I think having the props explained for VLCPlayerView would help a ton.

**Comment by Usman-02501** [comment]
Hi how to add play/pause button and slider
