### ISSUE TITLE
Can't seek on android

### ISSUE THREAD

**Issue by cheeka13** [razorRun/react-native-vlc-media-player#175]
Guys I can't perform seeking or fast forwarding on Android.
Video always restarts after pressing seek button.
Did check the log cat but have no idea what's going on.

**Comment by cheeka13** [comment]
got it, in android/src/main/java/com/yuanzhou/vlc/vlcplayer/ReactVlcPlayerViewManager.java change line 120 from videoView.seekTo(Math.round(seek * 1000f)) to videoView.setPosition(seek)

**Comment by KevinNguyen263** [comment]
Thanks, i'm facing the same issue.

**Comment by R4tch3t** [comment]
or in JS if(Platform.OS==="android"){
   videoRef.current.seek(seekInMilis/1000); // or seekInSeconds
}
