### ISSUE TITLE
Previous video does not stop when a new one is placed

### ISSUE THREAD

**Issue by jansi-hernandez** [razorRun/react-native-vlc-media-player#185]
when I switch from one video to another, the previous one remains activated and the audio remains active.

**Comment by kelvinaliyanto** [comment]
i think it gets released in ios, but not in android

**Comment by anudeepreddy** [comment]
> i think it gets released in ios, but not in android

Version 1.0.66 should have the fix available for android

**Comment by kelvinaliyanto** [comment]
> > i think it gets released in ios, but not in android
> 
> Version 1.0.66 should have the fix available for android

No matching version found for react-native-vlc-media-player@^1.0.66 when i try to use npm.

**Comment by jansi-hernandez** [comment]
@kelvinaliyanto try to use it like this: 
"react-native-vlc-media-player": "git+https://github.com/razorRun/react-native-vlc-media-player.git
