### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RCTVLCPlayer" was not found in the UIManager.

### ISSUE THREAD

**Issue by ogeanvictor** [razorRun/react-native-vlc-media-player#186]
Using expo, I've done the mentioned steps on README but I'm still getting this error.

![image](https://github.com/razorRun/react-native-vlc-media-player/assets/110622694/bce82401-7366-4379-a2db-36834c16009c)

**Comment by danielakarwowska** [comment]
the same error, any solution?

**Comment by ogeanvictor** [comment]
Fix issue: 
First install expo-dev-client : `npx expo install expo-dev-client`.

VLCPlayer component is something like this:

`import { VLCPlayer } from 'react-native-vlc-media-player';

const calcVLCPlayerHeight = (windowWidth,aspetRatio) => {
  return windowWidth * aspetRatio;
};

<VLCPlayer
            source={{
              initType: 2,
              hwDecoderEnabled: 1,
              hwDecoderForced: 1,
              uri:
                'rtsp://stream.com',
              initOptions: [
                '--no-audio',
                '--rtsp-tcp',
                '--network-caching=150',
                '--rtsp-caching=150',
                '--no-stats',
                '--tcp-caching=150',
                '--realrtsp-caching=150',
              ],
            }}
            autoplay={true}
            autoAspectRatio={true}
            resizeMode="cover"
            isLive={true}
            autoReloadLive={true}
            style={{ height: calcVLCPlayerHeight( Dimensions.get('window').width, 3/4), marginTop: 30}}
          />
`
Behind make component, follow the steps:

1. Make a development build in expo with `npx expo prebuild --clean`
2. Run project with: `npx expo run:android` or `npx expo run:ios`. This builds your project according to your device. (Necessary a emulator android/ios)
3. With any changes, you need to start your project with `npx expo start --dev-client`


Sorry my english, I hope this works.

**Comment by danielakarwowska** [comment]
Omg, it works. Thank you so much, you've saved me 3 weeks of work. Thanks

**Comment by igorbacz** [comment]
> Fix issue: First install expo-dev-client : `npx expo install expo-dev-client`.
> 
> VLCPlayer component is something like this:
> 
> `import { VLCPlayer } from 'react-native-vlc-media-player';
> 
> const calcVLCPlayerHeight = (windowWidth,aspetRatio) => { return windowWidth * aspetRatio; };
> 
> <VLCPlayer source={{ initType: 2, hwDecoderEnabled: 1, hwDecoderForced: 1, uri: 'rtsp://stream.com', initOptions: [ '--no-audio', '--rtsp-tcp', '--network-caching=150', '--rtsp-caching=150', '--no-stats', '--tcp-caching=150', '--realrtsp-caching=150', ], }} autoplay={true} autoAspectRatio={true} resizeMode="cover" isLive={true} autoReloadLive={true} style={{ height: calcVLCPlayerHeight( Dimensions.get('window').width, 3/4), marginTop: 30}} /> ` Behind make component, follow the steps:
> 
> 1. Make a development build in expo with `npx expo prebuild --clean`
> 2. Run project with: `npx expo run:android` or `npx expo run:ios`. This builds your project according to your device. (Necessary a emulator android/ios)
> 3. With any changes, you need to start your project with `npx expo start --dev-client`
> 
> Sorry my english, I hope this works.

It works correctly on ios and android emulators but after publish (with command: eas update ). I've got the same error:requireNativeComponent: "RCTVLCPlayer" was not found in the UIManager.

Any idea why it doesn’t work after publish with expo on expo go app ?

**Comment by ogeanvictor** [comment]
> > Fix issue: First install expo-dev-client : `npx expo install expo-dev-client`.
> > VLCPlayer component is something like this:
> > `import { VLCPlayer } from 'react-native-vlc-media-player';
> > const calcVLCPlayerHeight = (windowWidth,aspetRatio) => { return windowWidth * aspetRatio; };
> > <VLCPlayer source={{ initType: 2, hwDecoderEnabled: 1, hwDecoderForced: 1, uri: 'rtsp://stream.com', initOptions: [ '--no-audio', '--rtsp-tcp', '--network-caching=150', '--rtsp-caching=150', '--no-stats', '--tcp-caching=150', '--realrtsp-caching=150', ], }} autoplay={true} autoAspectRatio={true} resizeMode="cover" isLive={true} autoReloadLive={true} style={{ height: calcVLCPlayerHeight( Dimensions.get('window').width, 3/4), marginTop: 30}} /> ` Behind make component, follow the steps:
> > 
> > 1. Make a development build in expo with `npx expo prebuild --clean`
> > 2. Run project with: `npx expo run:android` or `npx expo run:ios`. This builds your project according to your device. (Necessary a emulator android/ios)
> > 3. With any changes, you need to start your project with `npx expo start --dev-client`
> > 
> > Sorry my english, I hope this works.
> 
> It works correctly on ios and android emulators but after publish (with command: eas update ). I've got the same error:requireNativeComponent: "RCTVLCPlayer" was not found in the UIManager.
> 
> Any idea why it doesn’t work after publish with expo on expo go app ?

I guess its because when make a prebuild, and run project with `npx expo run:android` or `npx expo run:ios` its eject project from expo go, 'cause expo go doesn't support native libs from react-native. The project starts running only on emulators

**Comment by aisehiwebwala** [comment]
Hi. Please can anyone give me a sample code to run a video from url in vlcplayer, i am not much experienced in this, but really want to use it for my work, please anyone.

**Comment by ogeanvictor** [comment]
```
import { VLCPlayer } from 'react-native-vlc-media-player';

const calcVLCPlayerHeight = (windowWidth,aspetRatio) => {
return windowWidth * aspetRatio;
};

<VLCPlayer
source={{
initType: 2,
hwDecoderEnabled: 1,
hwDecoderForced: 1,
uri:
'rtsp://stream.com',
initOptions: [
'--no-audio',
'--rtsp-tcp',
'--network-caching=150',
'--rtsp-caching=150',
'--no-stats',
'--tcp-caching=150',
'--realrtsp-caching=150',
],
}}
autoplay={true}
autoAspectRatio={true}
resizeMode="cover"
isLive={true}
autoReloadLive={true}
style={{ height: calcVLCPlayerHeight( Dimensions.get('window').width, 3/4), marginTop: 30}}
/>

```

> Hi. Please can anyone give me a sample code to run a video from url in vlcplayer, i am not much experienced in this, but really want to use it for my work, please anyone.

**Comment by amjadmak** [comment]
I tried ```npx expo prebuild --clean``` and then ```npx expo run:android```  but nothing worked .


Also, I built two different versions, with plugins in ```app.json``` and without plugins, and still got the same error on both builds.

Any suggestions?

Note that ```expo-dev-client``` is also installed

**Comment by ogeanvictor** [comment]
> I tried `npx expo prebuild --clean` and then `npx expo run:android` but nothing worked .
> 
> Also, I built two different versions, with plugins in `app.json` and without plugins, and still got the same error on both builds.
> 
> Any suggestions?
> 
> Note that `expo-dev-client` is also installed

you started project with `npx expo start --dev-client` ? 
what errors you got ?

**Comment by amjadmak** [comment]
> > I tried `npx expo prebuild --clean` and then `npx expo run:android` but nothing worked .
> > Also, I built two different versions, with plugins in `app.json` and without plugins, and still got the same error on both builds.
> > Any suggestions?
> > Note that `expo-dev-client` is also installed
> 
> you started project with `npx expo start --dev-client` ? what errors you got ?

I will be listing all things that I tried here:

**1. when I run ```npx expo run:android```** the app will start automatically in the emulator

Here is what I see first:
![Untitled](https://github.com/razorRun/react-native-vlc-media-player/assets/95312230/727718bc-9a0f-4524-81d9-2d3ff9bb383f)


**2.** When I try to start the app from **Expo Go** and import ```<VLCPlayer/>``` component I receive this :
**```[Invariant Violation: requireNativeComponent: "RCTVLCPlayer" was not found in the UIManager.```**

**3.** When I use ```npx expo start --dev-client```  to open my development build, Here is what I got:

![image](https://github.com/razorRun/react-native-vlc-media-player/assets/95312230/2a23191d-4c0b-4c28-a4a7-2ac15f31603f)


I just entered a whirl with no solution, any suggestions?

**Comment by mvmmarcus** [comment]
hello, @amjadmak any update with your error, im getting the same error here :/

**Comment by amjadmak** [comment]
Hey, @mvmmarcus  .
Unfortunately, no updates. I could not use it.
I tried to use it for a hobby project, but since there is an error I just left the whole project.

I would like to see a solution though

**Comment by mvmmarcus** [comment]
@amjadmak tks for feedback. I will abort expo and build app with CLI :/

**Comment by amjadmak** [comment]
@mvmmarcus  before aborting Expo, you can try two options.
1. A different ```react native``` library that offers the same or similar feature.
2. Degrade your current ```react native``` version. I read that it works fine with previous ```react native``` versions.

**Comment by danielakarwowska** [comment]
Check how many versions of Expo you have in your package.json file. You can uninstall the libraries one by one and see if it works. Personally, I had the same problem. Upon carefully checking my package.json file, it turned out that I had 2 versions of Expo, both in dependencies and devDependencies.
