### ISSUE TITLE
"RCTVLCPlayer" was not found in the UIManager

### ISSUE THREAD

**Issue by RomanBorysenko** [razorRun/react-native-vlc-media-player#19]
Hello! 

I need help...

I try to play an rtsp feed on android and have an issue:
<img width="297" alt="Screenshot 2020-07-02 at 15 16 02" src="https://user-images.githubusercontent.com/25172102/86359474-b6abd280-bc79-11ea-93fa-e83813f72ca1.png">

**Comment by razorRun** [comment]
Whats the version of RN you are working on?. did you try cloning my example?

**Comment by razorRun** [comment]
Also, try without the wrapper [check this issue](https://github.com/razorRun/react-native-vlc-media-player/issues/4)
