### ISSUE TITLE
how to replay the video?

### ISSUE THREAD

**Issue by vanhungoz** [razorRun/react-native-vlc-media-player#20]
it is possible to replay the video?

**Comment by vanhungoz** [comment]
i use resume or seek functions, but it did not work

**Comment by vanhungoz** [comment]
currently, i use "key" property to replay video. it is just a trick.

**Comment by vokhuyetOz** [comment]
maybe we have to reimplement onEnd function in native code

**Comment by razorRun** [comment]
Yah. Most of the triggers on android need a bit of a touch. If you get a chance please have a look. Because I am bit tide up these days. Feel free to give a shout if you need a hand

**Comment by vokhuyetOz** [comment]
ah, @vanhungoz  is another my GitHub account. i think i will close it at that time, i will come back with it when i have time.

**Comment by HarishAppdeveloper** [comment]
can you give sample for replay

**Comment by sraza295** [comment]
> currently, i use "key" property to replay video. it is just a trick.

How did you replay your video?

**Comment by sraza295** [comment]
@HarishAppdeveloper @vokhuyetOz @razorRun 
This is working solution.

import React, { Component } from 'react';
import { View } from 'react-native';
import VLCPlayer from 'react-native-vlc-player';

class YourComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      // Your existing state variables
      // ...
      key: 1, // Add a key to force remounting of the VLCPlayer component
    };
  }

  onEnded() {
    // Seek to the beginning
    this.playerRef.seek(0);

    // Use setTimeout to ensure that seeking is complete before remounting the component
    setTimeout(() => {
      // Increment the key to force remounting of the VLCPlayer component
      this.setState((prevState) => ({ key: prevState.key + 1 }));
    }, 100);
  }

  render() {
    return (
      <View>
        {/* Force remounting by changing the key */}
        <VLCPlayer
          key={this.state.key}
          style={{
            width: this.state.width,
            height: this.state.Fullscreen
              ? this.state.orientation_change_height
              : '100%',
          }}
          autoplay={true}
          videoAspectRatio="16:9"
          resizeMode="fill"
          muted={this.state.muted}
          repeat={true}
          ref={(ref) => (this.playerRef = ref)}
          paused={this.state.paused}
          onProgress={this.progress}
          onEnd={this.onEnded.bind(this)}
          onBuffering={this.onBuffering.bind(this)}
          onError={this._onError}
          onStopped={this.onStopped.bind(this)}
          onPlaying={this.onPlaying.bind(this)}
          onPaused={this.onPaused.bind(this)}
          onLoad={this.load}
          source={{
            uri: this.state.video_uri_path,
            initType: 2,
            initOptions: ['--rtsp-tcp', '--no-stats'],
          }}
        />
      </View>
    );
  }
}

export default YourComponent;
