### ISSUE TITLE
Expo Couldn't find DSO to load

### ISSUE THREAD

**Issue by Wolfleader101** [razorRun/react-native-vlc-media-player#200]
Hello,

I am getting the following error when i try to create a custom expo development build with this project as a plugin.

`Couldn't find DSO to load: libhermes.so caused by: dlopen failed: cannot locate symbol "__emults_get_address"`

I am running expo 49.

**Comment by Wolfleader101** [comment]
#197  fixes this issue @razorRun 
However, npm needs to be updated to 1.0.68 as it isn't available on npm.

**Comment by tomas-lejdung** [comment]
I am having the same issue. Everything was working fine and then out of nowhere Android would no longer build (getting the same error as you). So I tried creating a new blank repo and only adding this package and getting the same error. No clue on how it worked initially if even a new repo is broken on start...

**Comment by amjadmak** [comment]
I am having the same issue as well
Why it is so difficult to use such a simple library?

**Comment by h3l1o5** [comment]
For anyone who is still struggling with this issue:

1. Just remove all **_react-native-vlc-media-player_** stuff inside the app.json plugins section.
2. Run `npx expo prebuild --clean`.
3. Run `./android/gradlew --stop` and then clean the Gradle caches with `rm -rf ~/.gradle/caches/`.
4. Run `npx expo run:android`.

This should resolve the issue.

Note: I'm using RN 0.74 and works fine on both iOS and Android, not sure if this still works with any other RN version.
