### ISSUE TITLE
Stuck on pod install forever

### ISSUE THREAD

**Issue by carlolucadei** [razorRun/react-native-vlc-media-player#206]
Hi guys,

starting from today, when I trying to use this package I got stuck at 'pod install'.

I also got the following error:

```bash
Installing MobileVLCKit (3.5.1)

[!] Error installina MobileVLCKit
aPods/1.13.0 cocoapods-downloader/1.6.3'
[!] /Users/XXXX/opt/anaconda3/bin/curl -f -L-o /var/folders/vz/dccd9qpx60q4f0ggn3005kdm0000gn/T/d20240610-34581-snjduu/file.txz https://download.videolan.org/pub/cocoapods/prod/MobileVLCKit-3.5.1-34408b84-e9eceaed.tar.xZ ...
```

![mobilevlckit](https://github.com/razorRun/react-native-vlc-media-player/assets/4101109/c62e724e-6574-4a80-94a4-c29e1871c4a2)

I also tried to download it manually, using the url provided by the error log, and it seems to me that something is not working on VLC servers.

Am I the only one with this issue?

**Comment by stephenlindauer** [comment]
Same issue here. I suspect issues on the VLC servers as well. Even using the videolan.org website last night was really sluggish.

**Comment by carlolucadei** [comment]
@stephenlindauer  I tried again some minutes ago, and it has been restored

**Comment by CVHOANG-coder** [comment]
I try 4g to connect internet. And it work.
run: pod install --verbose and check speed download
