### ISSUE TITLE
[Pod Install]

### ISSUE THREAD

**Issue by holengocson** [razorRun/react-native-vlc-media-player#22]
I cant install with Pod Install. It takes very long time and nothing happened. 
Have you met this case before ?

**Comment by razorRun** [comment]
Nope, It normally just works. have you tried the test project?

**Comment by mobile-simformsolutions** [comment]
same !! 
it freeze when podinstall and nothing happens 
any help  ?

**Comment by razorRun** [comment]
Can you try downgrading the version and let me know?
