### ISSUE TITLE
Bulding android missing vlcjni library

### ISSUE THREAD

**Issue by squallcs12** [razorRun/react-native-vlc-media-player#26]
Hi,

When I try to build release version, I got this issue

E/VLC/LibVLC: Can't load vlcjni library: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.eohjsc.eohmobile-pbXEfDFlJeKsdysX8qx0PQ==/lib/arm64/libvlcjni.so"

What should I do to overcome this issue?

**Comment by razorRun** [comment]
Can you please downgrade to 1.0.17 and let me know?

Because I do have several apps using that version and works fine for me

**Comment by niennguyen** [comment]
Hi razorRun
when i upgraded to org.videolan.android:libvlc-all:3.3.10 
i got same problem. Do you have any ideal to solve it?

Thank you

**Comment by razorRun** [comment]
Could you try the test repo?

**Comment by niennguyen** [comment]
@razorRun 

> Could you try the test repo?

Yes, same problem on test repo, when i upgraded to org.videolan.android:libvlc-all:3.3.10 version.
