### ISSUE TITLE
Erorr when npm i react-native-vlc-media-player --save

### ISSUE THREAD

**Issue by chaiyaphat12079** [razorRun/react-native-vlc-media-player#27]
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [:react-native-vlc-media-player] C:\Users\chaiy\Desktop\ProjectIOT\AwesomeProject\node_modules\react-native-vlc-media-player\android\build\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 17,
                or use tools:overrideLibrary="com.yuanzhou.vlc" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\Users\chaiy\Desktop\ProjectIOT\AwesomeProject\android\app\src\debug\AndroidManifest.xml Error:

C:\Users\chaiy\Desktop\ProjectIOT\AwesomeProject>

**Comment by razorRun** [comment]
You will have to increase the minSdk in the manifest. It might ask you to update android shared lib files. Have tried using the test repo I have setup.
