### ISSUE TITLE
zoom on focus support

### ISSUE THREAD

**Issue by RupamShaw** [razorRun/react-native-vlc-media-player#3]
is it possible to use react-native-gesture-handler to zoom video using this library. example please.I Used  react-native-nodemediaclient its working perfectly for rtmp but zoom functionality not supported. looking for new rtmp support library for it.

**Comment by ammarahm-ed** [comment]
@RupamShaw use something like https://www.npmjs.com/package/react-native-pinch-zoom-view for this purpose.
