### ISSUE TITLE
not working on react native 0.63

### ISSUE THREAD

**Issue by johnlanz** [razorRun/react-native-vlc-media-player#36]
its working fine on react native 0.61.5 but its not working on latest react 0.63.3

**Comment by devnullpointer** [comment]
Same here. Removed react-native-video and added vlc-media-player not getting this when I build.

Log:

> > Task :app:mergeDebugNativeLibs FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:mergeDebugNativeLibs'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
>    > More than one file was found with OS independent path 'lib/x86/libc++_shared.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
>

**Comment by razorRun** [comment]
I am working on it. Should be able to release by the end of next week.

**Comment by karanchaudhri** [comment]
@razorRun Any update on this?

**Comment by buyungb** [comment]
@razorRun Pardon me, any update for this issue. You are doing great work. Thanks

**Comment by MayanthaJ** [comment]
Please use this test repo https://github.com/razorRun/react-native-vlc-media-player-test
The package is working and tested on RN V0.63.4
