### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by grosbedos** [razorRun/react-native-vlc-media-player#4]
Hi,

I wanted to know how do you get the player to go full screen?
At the moment my video is played in thumbnail, and I would like to play it in full screen after a user intervention (press a button for example).

I haven't found a method to do this. 
If you can help me ;)

Best regards

**Comment by ammoradi** [comment]
any news on this?

**Comment by omerdn1** [comment]
@razorRun Any chance you can jump in on this?

**Comment by amerllica** [comment]
Dear @grosbedos, @ammoradi, @omerdn1 

Do not use `VlCPlayerView`, it's a simple wrapper to the `VLCPlayer`. I just use `VLCPlayer` and implement my UI. please see the `VlCPlayerView` source codes. It's very very simple and If I was in @razorRun place definitely I would delete the `VlCPlayerView`.

Dear @grosbedos, please close this issue. The @razorRun is on vacation.

**Comment by ammoradi** [comment]
@amerllica hey Amer nice to meet you here.
could you suggest a replacement for this lib?

**Comment by amerllica** [comment]
@ammoradi, This library is awesome, the best way to have a rich Video player is to have `vlckit` for play videos not using `AVFoundation` like damn `react-native-video`. Just because of this reason this library is awesome.

But some native-side functionalities have issues and I didn't find a better library for my desire than this current. in a new feature, I wanna finish a complete-featured Video player.

**Comment by ammoradi** [comment]
@amerllica thank you. I will continue using this lib then.

**Comment by zaptrem** [comment]
Is there any way to go "real" full screen with VLCPlayer and activate the native control interface? Currently, full screen just takes up the entire containing component instead of actually filling the whole *screen*.

**Comment by Usman-02501** [comment]
> Dear @grosbedos, @ammoradi, @omerdn1
> 
> Do not use `VlCPlayerView`, it's a simple wrapper to the `VLCPlayer`. I just use `VLCPlayer` and implement my UI. please see the `VlCPlayerView` source codes. It's very very simple and If I was in @razorRun place definitely I would delete the `VlCPlayerView`.
> 
> Dear @grosbedos, please close this issue. The @razorRun is on vacation.

please share your code where you implement 'VLCPlayer'
