### ISSUE TITLE
Not able to stream RTSP

### ISSUE THREAD

**Issue by shrynshjn** [razorRun/react-native-vlc-media-player#41]
I am trying to live stream using RTSP, the url is wokring fine in the actual media player but it just shows a black screen when trying to stream it using VLCPlayer

**Comment by rogerio-azevedo** [comment]
Still not work with RTSP, like DVR channel stream?

**Comment by razorRun** [comment]
Well I use it day today basis to play from NVRs and cameras.

Did you try the test app?

**Comment by rogerio-azevedo** [comment]
Hi razorRun thank you for your reply!!! No I didn't test it yet. I will and report you if it worked. Today, I have an App, and I get the IP Camera stream from a MPGEG secondary stream channel, but its not working good, because I'm using a WebView to render the stream :(

**Comment by razorRun** [comment]
Yap

Cameras was the main reason for us to develop/maintain this plugin. We have
many users that use latest of this to stream RTSP

Cheers

**Comment by rogerio-azevedo** [comment]
Hey **razorRun** I tried your rest app.

1) git clone
2) yarn
3) cd ios => pod install (it took 9 minutes to install)
4) cd..
5) replace you rtsp for my camera address
6) yarn ios

It woked like a charm!!!

Now, i will try to add it to my application! Do you intend to maintain this library, I suppose! Its the first lib I found to play RTSP stream with React-Native. Thank you!

**Comment by razorRun** [comment]
Yap hoping to.

But a helping hand to sort out some of existing issues are much appreciated.

**Comment by rogerio-azevedo** [comment]
Iam a newbie dev, but I will try to find someone to help out!

**Comment by rogerio-azevedo** [comment]
RazorRun Morning!!! This issue could be closed I suppose. Add me as a collaborator, I will try help out with issues. Even if I can't fix it, I can interact with the devs

**Comment by razorRun** [comment]
Will do, thanks!

**Comment by rogerio-azevedo** [comment]
Look my app with camera working!

[](https://prnt.sc/vzbnjw)

**Comment by shrynshjn** [comment]
I was able to get it working, after seeing the example I realized I have to pass certain options to RTSP to work.
Can we maybe kee[ default options according to the protocol in URL, and then if the user wishes to he can specify other options.
I am new in developing but I would like to work on this feature if it seems like something that can be/should be done.
