### ISSUE TITLE
Unable to resolve module `@react-native-community/toolbar-android`

### ISSUE THREAD

**Issue by rogerio-azevedo** [razorRun/react-native-vlc-media-player#47]
Error on new project, after import:

`import {VLCPlayer} from 'react-native-vlc-media-player'; `

Problem solved after:

`yarn add @react-native-community/toolbar-android`

Is this expected?

**Comment by pascal-mormin** [comment]
I have the same problem on Apple TV TvOs 14.3. 

The solution provide by @rogerio-azevedo is a temporary one. I think we don't have to install @react-native-community/toolbar-android to run on Apple devices only.

**Comment by rogerio-azevedo** [comment]
Hey @pascal-mormin I couldn't use in android, did you?
