### ISSUE TITLE
could smaller apk size, add all vlc ?

### ISSUE THREAD

**Issue by tianlu1677** [razorRun/react-native-vlc-media-player#48]
I use this component, it run very well. Before my apk is about 30M， add this my apk is 90M. I only playing video, do not use advanced function.

**Comment by leehave** [comment]
> I use this component, it run very well. Before my apk is about 30M， add this my apk is 90M. I only playing video, do not use advanced function.

你好，你是怎么解决的

**Comment by xiaoaren** [comment]
> > 我使用这个组件，它运行得很好。之前我的apk是30M左右，加上这个我的apk是90M。我只播放视频，不使用高级功能。
> 
> 你好，你是怎么解决的

https://blog.csdn.net/qq_34983989/article/details/77840089

**Comment by buildnewapp** [comment]
add apk build config :
       ndk {
            abiFilters 'armeabi-v7a'
        }


    defaultConfig {
        applicationId 'com.xxx.app'
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0"

        buildConfigField("boolean", "REACT_NATIVE_UNSTABLE_USE_RUNTIME_SCHEDULER_ALWAYS", (findProperty("reactNative.unstable_useRuntimeSchedulerAlways") ?: true).toString())

        ndk {
            abiFilters 'armeabi-v7a'
        }
    }
