### ISSUE TITLE
I can't reproduce video from udp 

### ISSUE THREAD

**Issue by jomiva** [razorRun/react-native-vlc-media-player#49]
Is there an additional config to use udp protocol?

**Comment by MBakhtiyor** [comment]
@jomiva Share please solution if you found.

**Comment by jomiva** [comment]
> @jomiva Share please solution if you found.

![image](https://user-images.githubusercontent.com/48603039/103467442-870f7d00-4d25-11eb-9245-839ba4c53ef9.png)
Your router needs to be capable to support IPTV, here's my config.
