### ISSUE TITLE
iOS app crashes on re render VLCPlayer component in release mode

### ISSUE THREAD

**Issue by TayyabaAslam3317** [razorRun/react-native-vlc-media-player#50]
iOS app crashes when vlc player component is rendered with a live video stream on http with mjpeg video type. But when I re render the same component for the same live video stream url, my iOS app is crashing. The same flow is working perfect for android and iOS debug mode apps.

**Comment by razorRun** [comment]
Have you checked our testing app?

**Comment by TayyabaAslam3317** [comment]
@razorRun app crashes when we render camera and vlc player at same time or when switching from vlc player (when stream is playing) to camera and then back to vlc player (at this point app crashes when playing just tries to start). I checked this for your testing app as well.

**Comment by aircliff** [comment]
Looks like this issue is still happening... any updates? @TayyabaAslam3317 have a found a solution to this?

**Comment by diegods-ferreira** [comment]
The issue is still happening for me in my iOS app.
