### ISSUE TITLE
How to add subtitles?

### ISSUE THREAD

**Issue by MonsterCurry** [razorRun/react-native-vlc-media-player#52]
I'm streaming a .mp4 from a local server, I was wondering, how can I add subtitles? using <VLCPlayer />

**Comment by Prophetaa** [comment]
@razorRun ?

**Comment by Zenyker** [comment]
@razorRun how can I get a list of subtitles and audio from a mkv file?, and how to set it up,
in other libraries uses onLoad,

**Comment by jonyhandoko** [comment]
@razorRun hai, I also want know can we add soft subtitle on this package?

**Comment by razorRun** [comment]
Hey Guys

At the moment that’s not working. We need to pass the subs to the underline
vlc in the same way we pass other params. Someone will have to undertake
this as I am bit busy these days. Maybe create a bounty and someone with
help you quite quickly

Cheers

**Comment by DevineDecrypter** [comment]
i want to load subtitles from a url , are there ways to do it ? or other packaged that are capable of doing this ?

**Comment by razorRun** [comment]
It depends on the format, as I told you earlier if you want something
urgent create a bug bounty
https://www.bountysource.com/ someone will attend to it. I don’t see how I
can get to this for next couple of months.

Cheers
