### ISSUE TITLE
how to use bitcode when archive

### ISSUE THREAD

**Issue by xralphack** [razorRun/react-native-vlc-media-player#53]
I did enable bitcode in my react-native root project, the following error show when I "archive" the ios part

ld: bitcode bundle could not be generated because 'xxx/ios/Pods/MobileVLCKit/MobileVLCKit.framework/MobileVLCKit(VLCEmbeddedDialogProvider.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file 'xxx/ios/Pods/MobileVLCKit/MobileVLCKit.framework/MobileVLCKit' for architecture armv7

**Comment by shrynshjn** [comment]
Hi, did you find a solution for this yet?
Having the same problem

**Comment by razorRun** [comment]
From the memory it does not work when you turn on the bit coding

**Comment by xralphack** [comment]
I just disabled bitcode...

**Comment by ntquang98** [comment]
Hi @xralphack , Is it work when disabled bitcode?

**Comment by xralphack** [comment]
@ntquang98 yes
