### ISSUE TITLE
Is it possible to set allowsExternalPlayback value to true in VLCPlayer?

### ISSUE THREAD

**Issue by SandeepKharbanda** [razorRun/react-native-vlc-media-player#60]
I want to play an iOS video on my Apple TV device using Airplay. So, is it possible to set the **allowsExternalPlayback** value to **true**, which will allow the VLC player to switch to external playback mode?

Any suggestion would be a great help.

**Comment by razorRun** [comment]
Hey

You will have to pass those to underline iOS and Android players. Please
take a look at how we have passed other params and you will have to
implement that part as I am bit busy at the moment. If you are not that
familiar maybe create bounty for that feature and someone will help you
out.

Cheers
