### ISSUE TITLE
Muted is not working

### ISSUE THREAD

**Issue by diego-layerx** [razorRun/react-native-vlc-media-player#61]
Hi guys, I'm working on a project that is using this package to stream videos.

I'm trying to mute the video, but it isn't working.

Does someone has implemented that property and had luck on it?

Below is my component:

```
<VLCPlayer
    style={[props.style, {height: height}]}
    videoAspectRatio="16:9"
    source={{uri: props.item[props.imageKey]}}
    // muted={props.item.muted}
    // muted
    muted={true}
    playInBackground={false}
    resizeMode="contain"
    seek={1}
/>
```

Thanks in advance!

Cheers

**Comment by SvitlanaTimofeyeva** [comment]
Hi 
In case anyone needs it, I have implemented "muted" prop for ios, you can check it here
https://github.com/SvitlanaTimofeyeva/react-native-vlc-media-player 

not an objective-c expert by any means, but at least it works )
