### ISSUE TITLE
Get aspect ratio

### ISSUE THREAD

**Issue by lule-steph** [razorRun/react-native-vlc-media-player#63]
Hi

To use your nice lib I need to get aspect ratio of the video.

Indeed if we don't know it how do you compute height of the component ?

Thank you

**Comment by razorRun** [comment]
I see that can be a issue, buy usually the meta data should have most of
those info. Other thing is I usually just use the full available space and
set the ratio according to the space and play it in there regardless of
original aspect ratio. But I understand that won’t always be an option.
What I would suggest is investigate the vlc original lib and see if they
have an option if so update the lib to use those. I will be more than happy
to accept PRs. Sorry couldn’t help you more as I am tide up with million
other things at the moment, but I am pretty sure if you put a bounty
someone will sort it out

Cheers

**Comment by lule-steph** [comment]
Thank you for your answer!

Could you please provide some useful links for the vlc original lib so I can investigate in that direction.

If I find a solution it will be a pleasure to provide a PR !
