### ISSUE TITLE
The Prop Volume is Not Working

### ISSUE THREAD

**Issue by redefinered** [razorRun/react-native-vlc-media-player#65]
I tried 1 - 10 then 1 - 100 the volume does not change

library versions:
`react-native: 0.63.3`
`react-native-vlc-media-player: 1.0.30`

**Comment by razorRun** [comment]
New feature requests and bug fixes
At the moment I am a bit tied up with other work. As a matter of fact, I don't get much time to develop at all nowadays. But I am more than open to help anyone who wants's to contribute to this repo. And I will be sure to merge any fixes as soon as PR's come up. But if you need someone to fix issues that affect you till I get back to this(ETA Q3 2022), One option is to add a bounty to the following site https://www.bountysource.com/ someone will attend to it.
