### ISSUE TITLE
Playing HLS m3u8 links crash the app

### ISSUE THREAD

**Issue by andy-io** [razorRun/react-native-vlc-media-player#67]
Hi,

i tried to play this link https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

But it is crashing the app.
in the logcat i see the following: 
04-29 11:55:22.702  4076 12646 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 12646 (VlcObject), pid 4076 (m.myapp)
04-29 11:55:22.799 12657 12657 E DEBUG   : failed to readlink /proc/12646/fd/218: No such file or directory
04-29 11:55:22.799 12657 12657 E DEBUG   : failed to readlink /proc/12646/fd/246: No such file or directory

please help me to solve this issue

**Comment by redefinered** [comment]
hi @andy-io same here. have you found a fix on the issue?

**Comment by andy-io** [comment]
@redefinered  : no i didnt manage to solve this issue.

If url has .m3u8 in it then use react-native-video library. this is my temporary solution

**Comment by razorRun** [comment]
New feature requests and bug fixes
At the moment I am a bit tied up with other work. As a matter of fact, I don't get much time to develop at all nowadays. But I am more than open to help anyone who wants's to contribute to this repo. And I will be sure to merge any fixes as soon as PR's come up. But if you need someone to fix issues that affect you till I get back to this(ETA Q3 2022), One option is to add a bounty to the following site https://www.bountysource.com/ someone will attend to it.
