### ISSUE TITLE
Xcode12 Linker Error

### ISSUE THREAD

**Issue by juniortrials** [razorRun/react-native-vlc-media-player#68]
hello all good, now Apple requires compiling apps on Xcode 12 and SDK 14 https://developer.apple.com/news/?id=ib31uj1j when upgrading to Xcode 12 this error occurred while compiling the app, is there any solution ? thank you so much
<img width="1177" alt="Screen Shot 2021-05-02 at 15 42 37" src="https://user-images.githubusercontent.com/7092489/116823868-5ddced00-ab5d-11eb-8033-98bbe4b8b86c.png">

**Comment by razorRun** [comment]
New feature requests and bug fixes
At the moment I am a bit tied up with other work. As a matter of fact, I don't get much time to develop at all nowadays. But I am more than open to help anyone who wants's to contribute to this repo. And I will be sure to merge any fixes as soon as PR's come up. But if you need someone to fix issues that affect you till I get back to this(ETA Q3 2022), One option is to add a bounty to the following site https://www.bountysource.com/ someone will attend to it.
