### ISSUE TITLE
rtmp  video freezes

### ISSUE THREAD

**Issue by alvarogeovani** [razorRun/react-native-vlc-media-player#69]
I am trying to display this video rtmp://stmv1.voxtvhd.com.br/armonytv/armonytv o rtsp: //stmv1.voxtvhd.com.br/armonytv/armonytv o  rtsp: //stmv1.voxtvhd.com.br/armonytv/armonytv
But after a minute the video freezes, what can it be?

**Comment by razorRun** [comment]
New feature requests and bug fixes
At the moment I am a bit tied up with other work. As a matter of fact, I don't get much time to develop at all nowadays. But I am more than open to help anyone who wants's to contribute to this repo. And I will be sure to merge any fixes as soon as PR's come up. But if you need someone to fix issues that affect you till I get back to this(ETA Q3 2022), One option is to add a bounty to the following site https://www.bountysource.com/ someone will attend to it.
