### ISSUE TITLE
The player does not work in background mode.

### ISSUE THREAD

**Issue by gHashTag** [razorRun/react-native-vlc-media-player#71]
The player does not work in background mode.

`<VLCPlayer source={{ uri: PlayButtonStore.uri }} playInBackground /> `

<img width="647" alt="Снимок экрана 2021-05-18 в 10 26 54" src="https://user-images.githubusercontent.com/6774813/118594902-94ed0880-b7c3-11eb-93d9-cb664868e4d5.png">

**Comment by razorRun** [comment]
New feature requests and bug fixes
At the moment I am a bit tied up with other work. As a matter of fact, I don't get much time to develop at all nowadays. But I am more than open to help anyone who wants's to contribute to this repo. And I will be sure to merge any fixes as soon as PR's come up. But if you need someone to fix issues that affect you till I get back to this(ETA Q3 2022), One option is to add a bounty to the following site https://www.bountysource.com/ someone will attend to it.
