### ISSUE TITLE
Can't load vlcjn library: libvlcjni.so

### ISSUE THREAD

**Issue by cyprianG96** [razorRun/react-native-vlc-media-player#73]
Hi, I have this error as below. Any ideas how to solve that? Downgrade to 1.0.17 not help(I saw last issue with same situation)

Can't load vlcjni library: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.app/lib/arm/libvlcjni.so"

**Comment by ReactRaylogic** [comment]
facing same issue.
RTSP video stream fine on debug mode but the app crashes on loading the component itself on prod.
