### ISSUE TITLE
onBuffering in IOS

### ISSUE THREAD

**Issue by HP161** [razorRun/react-native-vlc-media-player#76]
Plesae help me!
I can't use onBuffering in IOS.
----------------------------------------
here my code:
const loadingBuff = (event) => {
        if (event.bufferRate == 100){
            setLoading(false)
        }
    };
========================
  onBuffering={loadingBuff}

**Comment by PervezBellary** [comment]
Hi @HP161  any progress on this issue. were you able to solve it..?
