### ISSUE TITLE
Can't merge user_target_xcconfig with RN Reanimated Error

### ISSUE THREAD

**Issue by kimtj12** [razorRun/react-native-vlc-media-player#77]
I wanted to use rn vlc player with React Navigation and got this error below on `pod install`

`Can't merge user_target_xcconfig for pod targets: ["MobileVLCKit", "RNReanimated"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.`

Does anyone know how to fix this issue??

**Comment by vgaicuks** [comment]
You have to update MobileVLCKit to the 3.3.17 version. I created pull request ae39cc410db3dbcf5ca0a11ebe5c2c4d257c8204

**Comment by kimtj12** [comment]
Got it fixed thank you!
