### ISSUE TITLE
Header support

### ISSUE THREAD

**Issue by Michael24884** [razorRun/react-native-vlc-media-player#8]
As the title suggests, are there any possibility to add custom headers, I need to include a referrer header in some requests

**Comment by razorRun** [comment]
We can certainly look into this.

Please do an initial PR maybe. Then we can work with you on it?

**Comment by jhanzaibkhadim199** [comment]
Any update on this ? 
I need to send a header referer to play video unable to do this. 
Any help will be appreciated.
