### ISSUE TITLE
Preventing Local Network Privacy Permissions Alert in iOS 14

### ISSUE THREAD

**Issue by thuylt997** [razorRun/react-native-vlc-media-player#81]
## My Environment
* Plugin version: 1.0.29
* Platform: iOS only
* OS version: iOS 14
* Device manufacturer / model: iOS devices
* React Native version (`react-native -v`): 0.63.4

## Actual Behavior
My application on iOS devices running on iOS 14 show the Alert “[MyApp] would like to find and connect to devices on your local network” when the specific screen is loading RTSP link.

## Expected Behavior
What I want is when I access to the specific screen which using this plugin, I do not wanna see the Alert anymore.

## Steps to Reproduce

1. Launch the application.
2. Access to the screen (supposed the screen is X) which loading RTSP link.
3. When I access to X from another screen, the X show the Alert "[MyApp] would like to find and connect to devices on your local network".

## Context
I knew that iOS 14 request users must add support for local network privacy permissions and the behavior above is only show on iOS devices running on iOS 14 and later. But I do not really need this behavior appear in the screen X.
Simply, I wanna load the RTSP link. Why do I need to grant permission of finding and connecting to devices on my local network? 
Is there any methods to prevent this behavior or could I grant permission for this request when I launch the application, the Alert is not showing to users and its automatically understand that users has accepted the permission.

I really appreciate any help!
Thanks a million.

**Comment by thuyducati** [comment]
@razorRun Could you help me, please?

**Comment by razorRun** [comment]
Hey
I think this is managed from iOS it self if you add permissions to the
plist, it should ask once and save it. Did you request permissions that
way?

**Comment by thuyducati** [comment]
@razorRun 
> Hey I think this is managed from iOS it self 
> 
Yes, this behavior is managed from iOS it self but you can refer the link below. This will talk about the Local Network Privacy in iOS 14 from Apple, and its said that
> There is no API to explicitly bring up the local network privacy alert
>
Local Network Privacy: https://developer.apple.com/forums/thread/663888

> if you add permissions to the plist, it should ask once and save it. Did you request permissions that way?
>
As I said above, I do not add or request any permissions in Info.plist. When I am in iOS 13, there is no alert or any request for local network privacy permissions. But when I upgrade to iOS 14, this behavior is happened as I mentioned and this behavior is actually happened on iOS devices running on iOS 14.

My application does not support local network sharing and I just want to show the real time streaming using RTSP link. Is there any methods to prevent this behavior?

**Comment by thuyducati** [comment]
@razorRun
Excuse me, razorRun. Could you help me, please?
Our team and I are using your plugin to perform real time streaming. After we upgraded our iOS devices to iOS 14, we've got the issue above.
I hope to see your answer.
Thank you so much, razorRun!

**Comment by razorRun** [comment]
Hey

I think probably this get triggered because of the VLC version. We might
have to update it … have you test using my test repo ? Because the app I
develop this plugin works on iOS to stream rtsp cameras without an issue..

**Comment by accesssolid** [comment]
Do we have any updates on this issue?
In my case, when a user chooses 'Don't Allow,' the stream works in 3 seconds, but if the user presses 'Allow,' it takes 40 seconds.
I would like to remove and get rid of this popup @razorRun, please update the library or let me know if you have found any resolution for this.
Thanks!
