### ISSUE TITLE
Could not GET 'https://dl.bintray.com/videolan/Android/com/facebook/react/react-native/maven-metadata.xml'.

### ISSUE THREAD

**Issue by onebean06** [razorRun/react-native-vlc-media-player#94]
recently when I install vlc media player lib in android, the android studio show the error issue:
Could not GET 'https://dl.bintray.com/videolan/Android/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
it's never happened before, did anyone face the same issue ？how can I solve it？

**Comment by ludashen** [comment]
use "https://mvnrepository.com/artifact/org.videolan.android" replace before address!

**Comment by reubber** [comment]
> use "https://mvnrepository.com/artifact/org.videolan.android" replace before address!
it worked, thx
