### ISSUE TITLE
Detected multiple Kotlin daemon sessions at build\kotlin\sessions

### ISSUE THREAD

**Issue by mahmedmushtaq** [razorRun/react-native-vlc-media-player#96]
I installed the library and when I am trying to run yarn android it throws me an error 

`Task :app:mergeDebugNativeLibs FAILED
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings
389 actionable tasks: 378 executed, 11 up-to-date
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
   > More than one file was found with OS independent path 'lib/x86/libc++_shared.so'`
   
**Versions**
"react-native": "0.63.4",
"react-native-vlc-media-player": "^1.0.40"

**Comment by Z1hgq** [comment]
same error

**Comment by r3dm4n** [comment]
Same error for me ...
